### PR TITLE
Test coverage for const constructors

### LINKED ISSUE #140: Test coverage for const constructors
As there is code Dart issue in collecting coverage for const constructors: https://github.com/dart-lang/sdk/issues/38934 we need to update our tests to make sure that:
1. We use final for variables that hold instances of classes with const constructors
2. Global linter rules for monorepo project are updated to exclude prefer_const_constructors for all files in 'test' folder
3. All tests checked to find and fix that const constructor coverage issue (known class - AuthenticationException)

### PR DESCRIPTION
**Pull request by solid-maxim**
Fixes #140

### CODE REVIEW

File: metrics/web/test/features/dashboard/domain/entities/metrics/performance_metric_test.dart [hunk 1]
```diff
@@ -0,0 +1,52 @@
+// https://github.com/software-platform/monorepo/issues/140
+// ignore_for_file: prefer_const_constructors
+import 'package:metrics/features/dashboard/domain/entities/collections/date_time_set.dart';
+import 'package:metrics/features/dashboard/domain/entities/metrics/build_performance.dart';
+import 'package:metrics/features/dashboard/domain/entities/metrics/performance_metric.dart';
+import 'package:test/test.dart';
+
+void main() {
+  group("PerformanceMetric", () {
```
Comment (illia-romanenko) [inline metrics/web/test/features/dashboard/domain/entities/metrics/performance_metric_test.dart:9]: Should we add a test that if no duration provided - duration is 0?

File: metrics/web/test/features/dashboard/presentation/widgets/placeholder_bar_test.dart [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+import 'package:flutter_test/flutter_test.dart';
+import 'package:metrics/features/dashboard/presentation/widgets/colored_bar.dart';
+import 'package:metrics/features/dashboard/presentation/widgets/placeholder_bar.dart';
+
+void main() {
+  const _width = 2.0;
+
+  group("PlaceholderBar", () {
+    testWidgets(
+      "displays the ColoredBar",
```
Comment (illia-romanenko) [inline metrics/web/test/features/dashboard/presentation/widgets/placeholder_bar_test.dart:14]: What if we add tests that will be understandable and closer to the specification/current understanding? Here are some examples:
"displays as short box" -> check container height
"displays as a bar with grey border" -> check ColoredBar border?
