### PR TITLE
Integrate Firebase Auth into the CI integrations

### LINKED ISSUE #137: [ci_integrations] add firebase authentication
As we are adding firebase authentication to the web client we also need to make sure that [ci_integrations] CLI client support it.

Assumptions:
Firebase Auth works well in firedart plugin

Tasks

- [ ]  Add firebase auth fields to the ci config (username/password)
- [ ] Perform Firebase Authentication using the information provided in ci config before sync start
- [ ] Make sure that Firebase Auth Exceptions are well integrated into the sync process and if any issue clear information is given to the user

### PR DESCRIPTION
**Pull request by vladlaba**
Fixes #137

## Checklist

- [x] Documented
- [x] Unit tested

### CODE REVIEW

File: metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart [hunk 1]
```diff
@@ -11,13 +12,34 @@ class FirestoreDestinationClientFactory
     implements
         DestinationClientFactory<FirestoreDestinationConfig,
             FirestoreDestinationClientAdapter> {
-  const FirestoreDestinationClientFactory();
+  /// The [FirebaseAuth] instance used to authenticate the Firestore client.
+  /// 
+  /// If this is `null` then the [FirebaseAuth.initialize] is used.
```
Comment (illia-romanenko) [inline metrics/ci_integrations/lib/destination/firestore/client_factory/firestore_destination_client_factory.dart:17]: It looks like this should be rather a constructor description rather than a private field.

File: metrics/ci_integrations/lib/destination/firestore/config/model/firestore_destination_config.dart [hunk 2]
```diff
@@ -11,22 +11,42 @@ class FirestoreDestinationConfig extends Equatable
...
   String get destinationProjectId => metricsProjectId;
 
-  /// Creates the [FirestoreDestinationConfig] with the given
-  /// [metricsProjectId] and [firebaseProjectId].
+  /// Creates the [FirestoreConfig] with the given [metricsProjectId].
   ///
-  /// Throws an [ArgumentError] if either the [metricsProjectId]
-  /// or [firebaseProjectId] is null.
+  /// All the arguments are required. Throws an [ArgumentError]
+  /// if one of them is `null`.
```
Comment (illia-romanenko) [inline metrics/ci_integrations/lib/destination/firestore/config/model/firestore_destination_config.dart:38]:
```suggestion
  /// if any of them is `null`.
```
